/// This file is auto generated by od_generator.

#include "kickcat/CoE/OD.h"

namespace kickcat::CoE
{
    void populateOD()
    {
        {
            static CoE::Object object
            {
                .index = 0x1018,
                .code = CoE::ObjectCode::RECORD,
                .name = "Identity Object",
                .entries{}
            };
            CoE::addEntry(object,0,8,7,static_cast<CoE::DataType>(5),"Subindex 000",0x4);
            CoE::addEntry(object,1,32,7,static_cast<CoE::DataType>(7),"Vendor ID",0x29c);
            CoE::addEntry(object,2,32,7,static_cast<CoE::DataType>(7),"Product code",0x32);
            CoE::addEntry(object,3,32,7,static_cast<CoE::DataType>(7),"Revision number",0x0);
            CoE::addEntry(object,4,32,7,static_cast<CoE::DataType>(7),"Serial number",0xcafedeca);
            CoE::dictionary().push_back(std::move(object));
        }

        {
            static CoE::Object object
            {
                .index = 0x1600,
                .code = CoE::ObjectCode::RECORD,
                .name = "RxPDO Map 1",
                .entries{}
            };
            CoE::addEntry(object,0,8,15,static_cast<CoE::DataType>(5),"Subindex 000",0x1);
            CoE::addEntry(object,1,32,15,static_cast<CoE::DataType>(7),"RxPDO Map 1 Element 1",0x10);
            CoE::dictionary().push_back(std::move(object));
        }

        {
            static CoE::Object object
            {
                .index = 0x1a00,
                .code = CoE::ObjectCode::RECORD,
                .name = "TxPDO Map 1",
                .entries{}
            };
            CoE::addEntry(object,0,8,15,static_cast<CoE::DataType>(5),"Subindex 000",0x1);
            CoE::addEntry(object,1,32,15,static_cast<CoE::DataType>(7),"TxPDO Map 1 Element 1",0xe0);
            CoE::dictionary().push_back(std::move(object));
        }

        {
            static CoE::Object object
            {
                .index = 0x1c00,
                .code = CoE::ObjectCode::ARRAY,
                .name = "Sync manager type",
                .entries{}
            };
            CoE::addEntry(object,0,8,7,static_cast<CoE::DataType>(5),"Subindex 0",0x4);
            CoE::addEntry(object,1,8,7,static_cast<CoE::DataType>(5),"Subindex 1",0x1);
            CoE::addEntry(object,2,8,7,static_cast<CoE::DataType>(5),"Subindex 2",0x2);
            CoE::addEntry(object,3,8,7,static_cast<CoE::DataType>(5),"Subindex 3",0x3);
            CoE::addEntry(object,4,8,7,static_cast<CoE::DataType>(5),"Subindex 4",0x4);
            CoE::dictionary().push_back(std::move(object));
        }

        {
            static CoE::Object object
            {
                .index = 0x1c12,
                .code = CoE::ObjectCode::RECORD,
                .name = "RxPDO assign",
                .entries{}
            };
            CoE::addEntry(object,0,8,15,static_cast<CoE::DataType>(5),"Subindex 000",0x1);
            CoE::addEntry(object,1,32,15,static_cast<CoE::DataType>(7),"RxPDO assign Element 1",0x1600);
            CoE::dictionary().push_back(std::move(object));
        }

        {
            static CoE::Object object
            {
                .index = 0x1c13,
                .code = CoE::ObjectCode::RECORD,
                .name = "TxPDO assign",
                .entries{}
            };
            CoE::addEntry(object,0,8,15,static_cast<CoE::DataType>(5),"Subindex 000",0x1);
            CoE::addEntry(object,1,32,15,static_cast<CoE::DataType>(7),"TxPDO assign Element 1",0x1a00);
            CoE::dictionary().push_back(std::move(object));
        }

    }
}
