#!/bin/bash
# Single source of truth for KickCAT build options.
# Sourced by configure.sh and setup_build.sh.

declare -A OPT_DEFAULTS=(
    [unit_tests]=OFF
    [master_examples]=ON
    [slave_examples]=ON
    [esi_parser]=ON
    [simulation]=ON
    [tools]=ON
    [code_coverage]=OFF
    [af_xdp]=OFF
    [tsan]=OFF
)

declare -A OPT_DESCRIPTIONS=(
    [unit_tests]="Build unit tests"
    [master_examples]="Build master examples"
    [slave_examples]="Build slave examples"
    [esi_parser]="Enable ESI XML parser"
    [simulation]="Build simulation"
    [tools]="Build tools"
    [code_coverage]="Enable code coverage"
    [af_xdp]="Enable AF_XDP socket"
    [tsan]="Enable ThreadSanitizer"
)

declare -A OPT_CMAKE_FLAGS=(
    [unit_tests]="BUILD_UNIT_TESTS"
    [master_examples]="BUILD_MASTER_EXAMPLES"
    [slave_examples]="BUILD_SLAVE_EXAMPLES"
    [esi_parser]="ENABLE_ESI_PARSER"
    [simulation]="BUILD_SIMULATION"
    [tools]="BUILD_TOOLS"
    [code_coverage]="ENABLE_CODE_COVERAGE"
    [af_xdp]="ENABLE_AF_XDP"
    [tsan]="ENABLE_TSAN"
)

# Only options that gate a Conan dependency
declare -A OPT_CONAN_FLAGS=(
    [unit_tests]="unit_tests"
    [master_examples]="master_examples"
    [esi_parser]="esi_parser"
    [simulation]="simulation"
    [tools]="tools"
)

# Load .buildconfig into the CONFIG associative array.
# Requires CONFIG_FILE to be set before calling.
load_buildconfig() {
    declare -gA CONFIG
    for key in "${!OPT_DEFAULTS[@]}"; do
        CONFIG[$key]="${OPT_DEFAULTS[$key]}"
    done

    if [ -f "$CONFIG_FILE" ]; then
        while IFS='=' read -r key value; do
            [[ -z "$key" || "$key" == \#* ]] && continue
            key=$(echo "$key" | xargs)
            value=$(echo "$value" | xargs)
            if [[ -v "OPT_DEFAULTS[$key]" ]]; then
                CONFIG[$key]="$value"
            else
                warn "Unknown option in $CONFIG_FILE: $key (ignored)"
            fi
        done < "$CONFIG_FILE"
    fi
}

# Save the CONFIG associative array to .buildconfig.
# Requires CONFIG_FILE to be set before calling.
save_buildconfig() {
    {
        echo "# KickCAT build configuration"
        echo "# Generated by scripts/configure.sh — do not edit manually"
        for key in $(echo "${!CONFIG[@]}" | tr ' ' '\n' | sort); do
            echo "$key=${CONFIG[$key]}"
        done
    } > "$CONFIG_FILE"
}

# Print the current CONFIG values.
show_buildconfig() {
    if [ ! -f "$CONFIG_FILE" ]; then
        info "No .buildconfig found, showing defaults:"
    else
        info "Current configuration ($CONFIG_FILE):"
    fi
    for key in $(echo "${!CONFIG[@]}" | tr ' ' '\n' | sort); do
        printf "  %-20s %s\n" "$key" "${CONFIG[$key]}"
    done
}
