name: Quality

# read-write repo token
# access to secrets
on:
  workflow_run:
    workflows: ["PR build"]
    types:
      - completed

jobs:
  quality:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    steps:
      - name: 'Download artifact'
        uses: actions/download-artifact@v4
        with:
          pattern: coverage

      - name: coverage
        uses: 5monkeys/cobertura-action@master
        with:
            path: coverage_xml.xml
            minimum_coverage: 75
            show_line: true
            show_branch: true
